mission:
  navigation_mode: relative
  takeoff_altitude_m: 5.0
  speed_m_s: 2.0

  relative_waypoints:
    - { name: A, distance_m: 0, azimuth_deg: 0 }
    - { name: B, distance_m: 10, azimuth_deg: 90 }
    - { name: C, distance_m: 10, azimuth_deg: 180 }
    - { name: D, distance_m: 10, azimuth_deg: 270 }

  absolute_waypoints:
    - { name: A, latitude_deg: 37.103103, longitude_deg: -3.678049 }
    - { name: B, latitude_deg: 37.103263, longitude_deg: -3.678186 }
    - { name: C, latitude_deg: 37.103397, longitude_deg: -3.677959 }
    - { name: D, latitude_deg: 37.103241, longitude_deg: -3.677816 }
